config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'top#index'
  get 'mypage/:id' => 'top#mypage'
  resources :users
  
  resources :users, only: :show do 
    resources :menus
    resources :trainings do 
      collection do
        get :top
      end
    end
  end
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/item_in_menu.rb
class ItemInMenu < ApplicationRecord
    
    belongs_to :menu
    belongs_to :training
end

app/models/menu.rb
class Menu < ApplicationRecord
    validates :name, presence: :true
    validates :user_id, presence: :true
    
    
    belongs_to :user
    has_many :trainings, through: :training_in_menus, source: :training
    has_many :training_menus, dependent: :destroy
    accepts_nested_attributes_for :training_menus
end

app/models/training.rb
class Training < ApplicationRecord
    validates :name, :category_id, :user_id, :weight, :times, presence: true
    belongs_to :user
end

app/models/training_menu.rb
class TrainingMenu < ApplicationRecord
    
    belongs_to :menu
    belongs_to :training
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
  has_one_attached :image 
  has_many :trainings, dependent: :destroy
  has_many :menus, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :configure_permitted_parameters, if: :devise_controller?
    
    def configure_permitted_parameters
        devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
    end
end

app/controllers/menus_controller.rb
class MenusController < ApplicationController
    def new
        @user = User.find(params[:user_id])
        @trainings = @user.trainings
        @menu = Menu.new
        # jsファイル内でtrainingsデータを使用するための変数
        gon.trainings = @trainings
    end
    
    def create
        # binding.pry
        menu = Menu.create(params_menu)
        redirect_to top_user_trainings_path(current_user)
    end
    
    private
    def params_menu
        params.require(:menu).permit(:user_id, :name, training_menus_attributes: [:training_id, :weight, :times])
    end
end

app/controllers/top_controller.rb
class TopController < ApplicationController
    def top
    end
    
    def mypage
    end
end

app/controllers/trainings_controller.rb
class TrainingsController < ApplicationController
    def top
        @user = User.find(params[:user_id])
        @trainings = @user.trainings
    end
    
    def show
    end
    
    def new
        @user = User.find(params[:user_id])
        @training = Training.new
    end
    
    def create
        training = Training.create(params_training)
        # binding.pry
        redirect_to menu_user_trainings_path(current_user.id)
    end
    
    def edit
        @user = User.find(params[:user_id])
        @training = Training.find(params[:id])
    end
    
    def update
        training = Training.find(params[:id])
        training.update(params_training)
        
        redirect_to menu_user_trainings_path(current_user.id)
    end
    
    private
    def params_training
        params.require(:training).permit(:name,:user_id,:category_id,:weight,:times)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    def show
        @user = User.find(params[:id]) 
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/menus_helper.rb
module MenusHelper
end

app/helpers/top_helper.rb
module TopHelper
end

app/helpers/trainings_helper.rb
module TrainingsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
    <head>
        <title>Fitstack</title>
        <%= csrf_meta_tags %>
        <%= csp_meta_tag %>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
        <%= include_gon %>
        <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
        <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    </head>

    <body>
        <header>
            <h2>Fitstack</h2>
            <!--ハンバーガーボタン-->
            <div id="navToggle">
                <div>
                    <span class="top"></span> 
                    <span class="middle"></span> 
                    <span class="bottom"></span>
                </div>
            </div>
            <!--メニュー表示-->
            <nav>
                <% if user_signed_in? %>
                    <ul>
                        <li>
                            <%= link_to "マイページ","/mypage/#{current_user.id}" %>
                        </li>
                        <li>
                            <%= link_to "ユーザー情報",user_path(current_user) %>
                        </li>
                        <li>
                            <%= link_to "トレーニング一覧",top_user_trainings_path(current_user) %>
                            
                        </li>
                        <li>
                            <%= link_to "トレーニング登録",new_user_training_path(current_user) %>
                        </li>
                        <li>
                            <%= link_to "今日のトレーニング作成",new_user_menu_path(current_user) %>
                        </li>
                        <li>
                            <%= link_to "ログアウト", destroy_user_session_path, method: :delete %>
                        </li>
                        
                    </ul>
                <% else %>
                    <ul>
                        <li>
                            <%= link_to "ログイン",new_user_session_path %> 
                        </li>
                        <li>
                            <%= link_to "会員登録",new_user_registration_path %>
                            </li>
                        <li><a href="#">MENU2</a></li>
                    </ul>
                <% end %>
                
            </nav>
            
            
        </header>
        <main>
            <%= yield %>
        </main>
        
    </body>
</html>

app/views/menus/_training.html.erb
<div id="item-<%= training.id %>" class="content col-sm-12 col-md-3 text-center">
    <div class="content-panel">
        <div class="name">
            <p><%= training.name %></p>
        </div>
        <div class="logo">
            <img src="/assets/mustle_training.png">
        </div>
        <!--<div class="category">-->
        <!--    <p><%= training.category_id %></p>-->
        <!--</div>-->
        <!--<div class="weight">-->
        <!--    <p><%= training.weight %>kg</p>-->
        <!--</div>-->
        <!--<div class="times">-->
        <!--    <p><%= training.times %>回</p>-->
        <!--</div>-->
    </div>
</div>

app/views/menus/new.html.erb
<main id="new-menu">
    <section class="title">
        <h2>メニューの新規作成</h2>
    </section>
    
    <section class="content">
        <%= form_for [@user,@menu] do |f| %>
            <%=  f.hidden_field :user_id, value: current_user.id %>
            <div class="name">
                <%= f.label :name %>
                <%= f.text_field :name, placeholder: "メニュー名" %>
            </div>
            
            <div class="training-items">
                <p>ここに要素を追加していく</p>
            </div>
            
            <div class="add-training">
                <a class="add">+種目の追加</a>
                <hr>
            </div>
            
            <div class="submit">
                <%= f.submit "決定" %>
            </div>
        <% end %>
    </section>
    
    <!--モーダルの記述-->
    <section id="modal" class="hide">
        <section class="items row">
            <%= render partial: "training", collection: @trainings %>
        </section>
    </section>
    
    
    <%= javascript_include_tag 'menus.js' %>
</main>

app/views/top/mypage.html.erb
<p class="container">fgdfasfsadfsafsafd</p>

app/views/trainings/_training.html.erb
<div class="content col-sm-12 col-md-3 text-center">
    <%= link_to user_training_path(@user,training.id) do %>
        <div class="content-panel">
            <div class="name">
                <p><%= training.name %></p>
            </div>
            <div class="logo">
                <img src="/assets/mustle_training.png">
            </div>
            <div class="category">
                <p><%= training.category_id %></p>
            </div>
            <div class="weight">
                <p><%= training.weight %>kg</p>
            </div>
            <div class="times">
                <p><%= training.times %>回</p>
            </div>
        </div>
    <% end %>
</div>

app/views/trainings/edit.html.erb
<main id="training-edit">
    <section class="container">
        <%=  form_for [@user, @training] do |f| %>
            <div class="user-profile">
                <%= f.hidden_field :user_id, value: current_user.id %>
            </div>
            <div class="title">
                <%= f.label :name, "トレーニング名" %>
                <%= f.text_field :name, placeholder:"トレーニング名" %>
            </div>
            <div class="category">
                <%= f.label :category_id, "部位名" %>
                <%= f.text_field :category_id, placeholder:"半角数字で入力して下さい" %>
            </div>
            <div class="weight">
                <%= f.label :weight, "重量" %>
                <%= f.text_field :weight, placeholder:"半角数字で入力して下さい" %>
            </div>
            <div class="times">
                <%= f.label :times, "回数" %>
                <%= f.text_field :times, placeholder:"半角数字で入力して下さい" %>
            </div>
            <div class="submit">
                <%= f.submit "決定" %>
            </div>
        <% end %>
    </section>
</main>

app/views/trainings/menu.html.erb
<main id="training-show">
    <!--筋トレの種類-->
    <section class= "item container">
        <div class="title">
            <p class="text-center">トレーニング種目一覧</p>
        </div>
        
        <!--コンテンツをgridレイアウトで並べる,div括りだとrenderが繰り返されるたびに階層を上がってしまうのでsectionで括る-->
        <section class="contents row">
            <%= render partial: "training", collection: @trainings %>
        </section>
        
        <div class="add-item">
            <%= link_to "＋トレーニング種目の追加", new_user_training_path(@user) %>
        </div>
    </section>
    <!--トレーニングコースの種類-->
    <section class="course container">
        <div class="title">
            <p class="text-center">トレーニングメニュー一覧</p>
        </div>
        <div class="add-course">
            <%= link_to "＋トレーニングメニューの追加","" %>
        </div>
    </section>
</main>

app/views/trainings/new.html.erb
<main id="training-new">
    <section class="container">
        <%=  form_for [@user, @training] do |f| %>
            <%= f.hidden_field :user_id, value: current_user.id %>
            <div class="title">
                <%= f.label :name, "トレーニング名" %>
                <%= f.text_field :name, placeholder:"トレーニング名" %>
            </div>
            <div class="category">
                <%= f.label :category_id, "部位名" %>
                <%= f.text_field :category_id, placeholder:"部位を選択" %>
            </div>
            <div class="weight">
                <%= f.label :weight, "重量" %>
                <%= f.text_field :weight, type:"number", placeholder:"半角数字のみ" %>
            </div>
            <div class="times">
                <%= f.label :times, "回数" %>
                <%= f.text_field :times, type:"number", placeholder:"半角数字のみ" %>
            </div>
            <div class="submit">
                <%= f.submit "確定" %>
            </div>
        <% end %>
    </section>
</main>

app/views/trainings/show.html.erb
データグラフを挿入
編集、削除時にはポップアップを表示

app/views/trainings/top.html.erb
<main id="training-show">
    <!--筋トレの種類-->
    <section class= "trainings container">
        <div class="title">
            <p class="text-center">トレーニング種目一覧</p>
        </div>
        
        <!--コンテンツをgridレイアウトで並べる,div括りだとrenderが繰り返されるたびに階層を上がってしまうのでsectionで括る-->
        <section class="items row">
            <%= render partial: "training", collection: @trainings %>
        </section>
        
        <div class="add-item">
            <%= link_to "＋トレーニング種目の追加", new_user_training_path(@user) %>
        </div>
    </section>
    <!--トレーニングmenuの種類-->
    <section class="menus container">
        <div class="title">
            <p class="text-center">トレーニングメニュー一覧</p>
        </div>
        <section class="items row">
            <%= render partial: "training", collection: @trainings %>
        </section>
        <div class="add-item">
            <%= link_to "＋トレーニングメニューの追加","" %>
        </div>
    </section>
</main>

app/views/users/show.html.erb
<main class="profile">
    <div class="container">
        <div class="profile-user">
            <%= form_for @user do |f| %>
                <div class="user-image user-form">
                    <% if @user.image.attached? %>
                        <img src ="<%= rails_blob_path(@user.image) %>">
                    <% else %>
                        <img src="/assets/sheep.png">
                    <% end %>
                    <%= f.file_field :image, placeholder: "画像アップロード" %>
                </div>
                <div class="user-name user-form">
                    <%= f.label "ユーザー名" %>
                    <%= f.text_field :name %>
                </div>
                <div class="user-email user-form">
                    <%= f.label "メールアドレス" %>
                    <%= f.text_field :email %>
                </div>
                <div class="submit">
                    <%= f.submit "変更" %>
                </div>
            <% end %>
        </div>
        
    </div>
</main>